commonLabels:
  label-for: royston
  app: royston-nginx
  environment: production


ingress:
  enabled: true
  pathType: Prefix
  hostname: royston-nginx-hc.sctp-sandbox.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "royston-nginx-hc.sctp-sandbox.com"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  ingressClassName: "nginx"
  tls: true

podLabels:
  app: royston-nginx
  environment: production