apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ky-nginx-webapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests
    repoURL: https://github.com/kytan2992/assignment_3.14_pt2.git
    targetRevision: HEAD
  destination:
    namespace: ky-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
