commonLabels:
  label-for: jsstrn-nginx-label

replicaCount: 3

ingress:
  enabled: true
  pathType: Prefix
  hostname: jsstrn.sctp-sandbox.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "jsstrn.sctp-sandbox.com"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  ingressClassName: "nginx"
  tls: true
