apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stewart-nginx-hc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/StewartOng/argocd-demo
    targetRevision: HEAD
    chart: nginx
    helm:
      valueFiles:
        - manifests/stewart-nginx-hc/values.yaml
    path: ""  # Use empty if using remote Helm chart
  destination:
    server: https://kubernetes.default.svc
    namespace: stewart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
